const graph = {
  "meta":{
    "timestamp":1691800188821,
    "owner":"kleiner.masha@gmail.com",
    "graphRects":{
      "Echo":{
        "l":528,
        "t":48,
        "w":200,
        "h":76
      },
      "JSONata":{
        "l":288,
        "t":48,
        "w":200,
        "h":76
      },
      "Weather":{
        "l":384,
        "t":240,
        "w":200,
        "h":60
      },
      "MyLocation":{
        "l":32,
        "t":112,
        "w":200,
        "h":96
      },
      "GoogleMap":{
        "l":384,
        "t":144,
        "w":200,
        "h":76
      },
      "Panel":{
        "l":32,
        "t":224,
        "w":200,
        "h":96
      }
    },
    "description":"renders map and weather forecast for the current location",
    "id":"LocalWeather",
    "designerId":"Main",
    "readonly":true
  },
  "nodes":{
    "Main":{
      "type":"$library/Layout/Nodes/DesignerNode",
      "container":"root$panel#Container"
    },
    "Echo":{
      "type":"$library/EchoNode",
      "container":"Main$panel#Container"
    },
    "JSONata":{
      "type":"$library/JSONata/Nodes/JSONataNode",
      "container":"Main$panel#Container"
    },
    "Weather":{
      "type":"$library/Locale/Nodes/WeatherNode",
      "container":"Main$panel#Container"
    },
    "MyLocation":{
      "type":"$library/Locale/Nodes/MyLocationNode",
      "container":"Main$panel#Container"
    },
    "GoogleMap":{
      "type":"$library/Locale/Nodes/GoogleMapNode",
      "container":"Panel$panel#Container"
    },
    "Panel":{
      "type":"$library/Layout/Nodes/PanelNode",
      "container":"Main$panel#Container"
    }
  },
  "state":{
    "Main$designer$disabled":false,
    "Main$designer$style":"width: auto; height: auto;",
    "Main$panel$canvasLayout":"column",
    "MyLocation$location$address":"My Location",
    "Main$designer$layout":{
      "Geolocation":{
        "l":32,
        "t":32,
        "w":132,
        "h":132,
        "borderWidth":"var(--border-size-2)",
        "borderStyle":"solid"
      },
      "Echo3":{
        "l":400,
        "t":224,
        "w":287,
        "h":344,
        "borderWidth":"var(--border-size-2)",
        "borderStyle":"solid"
      },
      "Main":{
        "l":0,
        "t":0,
        "w":585,
        "h":436,
        "padding":"",
        "backgroundColor":"var(--xcolor-one)",
        "borderRadius":"",
        "height":"auto",
        "width":"auto",
        "flex":"1"
      },
      "Echo":{
        "l":32,
        "t":32,
        "w":132,
        "h":132,
        "borderWidth":"0",
        "borderStyle":"solid",
        "order":"1",
        "backgroundColor":"var(--xcolor-one)",
        "fontSize":"var(--font-size-4)",
        "height":"auto",
        "padding":"",
        "flex":"",
        "width":"auto"
      },
      "JSONata":{
        "l":32,
        "t":32,
        "w":132,
        "h":132,
        "borderWidth":"var(--border-size-2)",
        "borderStyle":"solid"
      },
      "Weather":{
        "l":32,
        "t":32,
        "w":132,
        "h":132,
        "borderWidth":"0",
        "borderStyle":"solid",
        "order":"2",
        "flex":"",
        "height":"auto",
        "backgroundColor":"var(--xcolor-one)",
        "padding":"var(--size-3)",
        "width":"auto"
      },
      "MyLocation":{
        "l":32,
        "t":32,
        "w":132,
        "h":132,
        "borderWidth":"var(--border-size-2)",
        "borderStyle":"solid"
      },
      "GoogleMap":{
        "l":0,
        "t":0,
        "w":789,
        "h":463,
        "borderWidth":"",
        "borderStyle":"solid",
        "width":"auto",
        "height":"auto",
        "flex":"1",
        "display":"",
        "position":"relative",
        "order":"2",
        "justifyContent":""
      },
      "SplitPanel":{
        "l":32,
        "t":32,
        "w":132,
        "h":132,
        "borderWidth":"var(--border-size-2)",
        "borderStyle":"solid",
        "width":"auto"
      },
      "Panel":{
        "l":32,
        "t":32,
        "w":132,
        "h":132,
        "borderWidth":"0",
        "borderStyle":"solid",
        "order":"3",
        "flex":"1",
        "width":"auto",
        "height":"auto"
      }
    },
    "JSONata$JSONata$expression":"$join([*[2], ', ', *[4]])",
    "Echo$echo$style":"text-align: center; flex:1; padding-top: 15px;"
  },
  "connections":{
    "Echo$echo$html":"JSONata$JSONata$result",
    "JSONata$JSONata$json":"MyLocation$location$geolocation",
    "Weather$weather$geolocation":"MyLocation$location$geolocation",
    "GoogleMap$map$geolocation":"MyLocation$location$geolocation"
  }
};
