const graph = {
  "meta":{
    "timestamp":1694546189843,
    "owner":"kleiner.masha@gmail.com",
    "graphRects":{
      "OpenAIText":{
        "l":336,
        "t":128,
        "w":200,
        "h":116
      },
      "ProgressBar":{
        "l":336,
        "t":272,
        "w":200,
        "h":156
      },
      "AskText":{
        "l":32,
        "t":256,
        "w":200,
        "h":116
      },
      "AnswerText":{
        "l":592,
        "t":256,
        "w":200,
        "h":60
      },
      "Button":{
        "l":32,
        "t":304,
        "w":200,
        "h":96
      },
      "VerticalPanel":{
        "l":32,
        "t":272,
        "w":200,
        "h":96
      },
      "DeviceUx":{
        "l":32,
        "t":16,
        "w":200,
        "h":76
      },
      "Listen":{
        "l":32,
        "t":128,
        "w":200,
        "h":96
      },
      "Speak":{
        "l":592,
        "t":16,
        "w":200,
        "h":116
      }
    },
    "description":"voice interface for OpenAI and listen and speak interface and listen and speak interface and listen and speak interface",
    "customLibraries":{
      
    },
    "readonly":false,
    "id":"OpenAIQnA",
    "designerId":"Main"
  },
  "nodes":{
    "Main":{
      "type":"$library/Layout/Nodes/DesignerNode",
      "container":"root$panel#Container"
    },
    "AskText":{
      "type":"$library/Fields/Nodes/TextFieldNode",
      "container":"VerticalPanel$panel#Container"
    },
    "AnswerText":{
      "type":"$library/Fields/Nodes/StaticTextNode",
      "container":"Main$panel#Container"
    },
    "OpenAIText":{
      "type":"$library/OpenAI/Nodes/OpenAITextNode",
      "container":"Main$panel#Container"
    },
    "ProgressBar":{
      "type":"$library/UX/Nodes/ProgressBarNode",
      "container":"Main$panel#Container"
    },
    "Button":{
      "type":"$library/Fields/Nodes/ButtonNode",
      "container":"VerticalPanel$panel#Container"
    },
    "VerticalPanel":{
      "type":"$library/Layout/Nodes/PanelNode",
      "container":"Main$panel#Container"
    },
    "DeviceUx":{
      "type":"$library/Media/Nodes/DeviceUxNode",
      "container":"Main$panel#Container"
    },
    "Listen":{
      "type":"$library/Media/Nodes/ListenNode",
      "container":"Main$panel#Container"
    },
    "Speak":{
      "type":"$library/Media/Nodes/SpeakNode",
      "container":"Main$panel#Container"
    }
  },
  "state":{
    "Main$designer$disabled":false,
    "Main$designer$style":"width: auto; height: auto;",
    "Main$panel$canvasLayout":"column",
    "ProgressBar$bar$height":2,
    "Button$button$action":"toggle",
    "VerticalPanel$panel$layout":"row",
    "Main$designer$layout":{
      "AskText":{
        "l":32,
        "t":64,
        "w":591,
        "h":53,
        "borderWidth":"",
        "borderStyle":"solid",
        "height":"auto",
        "order":"1",
        "padding":"var(--size-3)",
        "backgroundColor":"var(--xcolor-one)",
        "flex":"1",
        "width":"auto"
      },
      "AnswerText":{
        "l":32,
        "t":112,
        "w":593,
        "h":268,
        "borderWidth":"var(--border-size-1)",
        "borderStyle":"solid",
        "height":"auto",
        "backgroundColor":"var(--xcolor-one)",
        "padding":"var(--size-3)",
        "flex":"1",
        "order":"4",
        "borderRadius":"var(--radius-3)",
        "width":"auto"
      },
      "OpenAIText":{
        "l":32,
        "t":32,
        "w":132,
        "h":132,
        "borderWidth":"var(--border-size-2)",
        "borderStyle":"solid"
      },
      "ProgressBar":{
        "l":32,
        "t":32,
        "w":132,
        "h":132,
        "borderWidth":"0",
        "borderStyle":"solid",
        "height":"auto",
        "backgroundColor":"var(--xcolor-one)",
        "order":"3",
        "padding":"var(--size-2)",
        "width":"auto"
      },
      "Main":{
        "borderWidth":"var(--border-size-1)",
        "backgroundColor":"var(--xcolor-one)",
        "padding":"var(--size-2)",
        "borderRadius":"var(--radius-3)"
      },
      "Button":{
        "l":32,
        "t":32,
        "w":132,
        "h":132,
        "borderWidth":"",
        "borderStyle":"solid",
        "order":"2",
        "height":"auto",
        "width":"auto",
        "padding":"var(--size-3)",
        "justifyContent":"end"
      },
      "VerticalPanel":{
        "l":32,
        "t":32,
        "w":132,
        "h":132,
        "borderWidth":"var(--border-size-1)",
        "borderStyle":"solid",
        "height":"auto",
        "borderRadius":"var(--radius-3)",
        "flex":"",
        "width":"auto",
        "justifyContent":"start",
        "order":"2"
      },
      "DeviceUx":{
        "l":32,
        "t":32,
        "w":132,
        "h":132,
        "borderStyle":"solid",
        "order":"1",
        "padding":"var(--size-2)"
      },
      "Listen":{
        "l":32,
        "t":32,
        "w":132,
        "h":132,
        "borderStyle":"solid"
      },
      "Speak":{
        "l":32,
        "t":32,
        "w":132,
        "h":132,
        "borderStyle":"solid"
      }
    },
    "OpenAIText$OpenAIText$context":"provide brief informative answer to questions;\n",
    "AskText$field$label":"question",
    "ProgressBar$bar$interval":100,
    "Button$button$label":"Ask",
    "OpenAIText$OpenAIText$enabled":true
  },
  "connections":{
    "AnswerText$StaticText$text":"OpenAIText$OpenAIText$result",
    "OpenAIText$OpenAIText$prompt":"AskText$field$value",
    "ProgressBar$bar$inProgress":"OpenAIText$OpenAIText$working",
    "OpenAIText$OpenAIText$restart":"Button$button$value",
    "Listen$SpeechRecognizer$mediaDeviceState":"DeviceUx$deviceUx$mediaDeviceState",
    "AskText$field$value":"Listen$SpeechRecognizer$transcript",
    "Speak$SpeechSynthesizer$mediaDeviceState":"DeviceUx$deviceUx$mediaDeviceState",
    "Speak$SpeechSynthesizer$transcript":"OpenAIText$OpenAIText$result"
  }
};
