const graph = {
  "meta":{
    "timestamp":1688595734693,
    "owner":"kleiner.masha@gmail.com",
    "stylized":true,
    "graphRects":{
      "DeviceUx":{
        "l":16,
        "t":48,
        "w":200,
        "h":76
      },
      "Panel":{
        "l":16,
        "t":128,
        "w":200,
        "h":96
      },
      "UXToolbar":{
        "l":16,
        "t":224,
        "w":200,
        "h":76
      },
      "ImageComposite":{
        "l":608,
        "t":48,
        "w":200,
        "h":196
      },
      "Image3":{
        "l":848,
        "t":128,
        "w":200,
        "h":76
      },
      "FrameCapture":{
        "l":304,
        "t":48,
        "w":200,
        "h":76
      },
      "Holistic":{
        "l":288,
        "t":160,
        "w":200,
        "h":76
      },
      "VirtualPointer":{
        "l":288,
        "t":272,
        "w":200,
        "h":60
      },
      "PointerPoms":{
        "l":288,
        "t":368,
        "w":200,
        "h":136
      }
    },
    "description":"colorful fingerpainging on the streamed video",
    "id":"VideoFingerpaint",
    "designerId":"Main"
  },
  "nodes":{
    "Main":{
      "type":"$library/Layout/Nodes/DesignerNode",
      "container":"root$panel#Container"
    },
    "DeviceUx":{
      "type":"$library/Media/Nodes/DeviceUxNode",
      "container":"Panel$panel#Container"
    },
    "FrameCapture":{
      "type":"$library/Media/Nodes/FrameCaptureNode",
      "container":"Panel$panel#Container"
    },
    "Holistic":{
      "type":"$library/Mediapipe/Nodes/HolisticNode",
      "container":"Main$panel#Container"
    },
    "ImageComposite":{
      "type":"$library/Media/Nodes/ImageCompositeNode",
      "container":"Main$panel#Container"
    },
    "Image3":{
      "type":"$library/Media/Nodes/ImageNode",
      "container":"Panel$panel#Container"
    },
    "UXToolbar":{
      "type":"$library/UX/Nodes/UXToolbarNode",
      "container":"Panel$panel#Container"
    },
    "Panel":{
      "type":"$library/Layout/Nodes/PanelNode",
      "container":"Main$panel#Container"
    },
    "VirtualPointer":{
      "type":"$library/Mediapipe/Nodes/VirtualPointerNode",
      "container":"Main$panel#Container"
    },
    "PointerPoms":{
      "type":"$library/Mediapipe/Nodes/PointerPomsNode",
      "container":"Main$panel#Container"
    }
  },
  "state":{
    "Main$designer$disabled":false,
    "Main$designer$style":"width: auto; height: auto;",
    "Main$panel$canvasLayout":"column",
    "FrameCapture$FrameCapture$fps":30,
    "Panel$panel$layout":"column",
    "Image3$image$image":{
      "alt":"no image"
    },
    "Main$designer$layout":{
      "DeviceUx":{
        "l":16,
        "t":0,
        "w":384,
        "h":40,
        "borderWidth":"0",
        "borderStyle":"solid",
        "order":"1",
        "width":"auto",
        "height":"auto",
        "backgroundColor":"var(--xcolor-three)",
        "color":"var(--xcolor-four)",
        "padding":"var(--size-2)",
        "borderRadius":"var(--radius-3)",
        "justifyContent":"center",
        "alignItems":"center"
      },
      "FrameCapture":{
        "l":32,
        "t":32,
        "w":132,
        "h":132,
        "borderWidth":"var(--border-size-2)",
        "borderStyle":"solid",
        "color":"var(--xcolor-one)",
        "justifyContent":"center",
        "order":"",
        "backgroundColor":""
      },
      "Holistic":{
        "l":32,
        "t":32,
        "w":132,
        "h":132,
        "borderWidth":"var(--border-size-2)",
        "borderStyle":"solid"
      },
      "Image":{
        "l":16,
        "t":96,
        "w":132,
        "h":102,
        "borderWidth":"0",
        "borderStyle":"solid",
        "order":"2",
        "height":null
      },
      "Image2":{
        "l":144,
        "t":96,
        "w":132,
        "h":97,
        "borderWidth":"0",
        "borderStyle":"solid",
        "order":"3"
      },
      "ImageComposite":{
        "l":320,
        "t":64,
        "w":132,
        "h":132,
        "borderWidth":"var(--border-size-2)",
        "borderStyle":"solid"
      },
      "Image3":{
        "l":4,
        "t":38,
        "w":1042,
        "h":151,
        "borderWidth":"0",
        "borderStyle":"solid",
        "flex":"1",
        "order":"3",
        "width":"auto",
        "borderRadius":"var(--radius-round)",
        "backgroundColor":"var(--xcolor-three)"
      },
      "Main":{
        "l":0,
        "t":0,
        "w":1017,
        "h":559,
        "backgroundColor":"var(--xcolor-one)"
      },
      "Image4":{
        "l":272,
        "t":96,
        "w":127,
        "h":99,
        "borderWidth":"0",
        "borderStyle":"solid",
        "order":"4"
      },
      "UXToolbar":{
        "l":0,
        "t":38,
        "w":425,
        "h":62,
        "borderWidth":"0",
        "borderStyle":"solid",
        "backgroundColor":"var(--xcolor-three)",
        "height":"auto",
        "padding":"var(--size-3)",
        "flex":"none",
        "order":"3",
        "width":"auto",
        "borderRadius":"var(--radius-3)"
      },
      "SelectField":{
        "l":32,
        "t":32,
        "w":132,
        "h":132,
        "borderWidth":"var(--border-size-2)",
        "borderStyle":"solid"
      },
      "Panel":{
        "l":384,
        "t":32,
        "w":443,
        "h":332,
        "borderWidth":"var(--border-size-4)",
        "borderStyle":"solid",
        "padding":"var(--size-1)",
        "backgroundColor":"var(--xcolor-three)",
        "flex":"1",
        "color":"var(--xcolor-three)",
        "borderRadius":"var(--radius-round)",
        "justifyContent":""
      },
      "VirtualPointer":{
        "l":32,
        "t":32,
        "w":132,
        "h":132,
        "borderWidth":"var(--border-size-2)",
        "borderStyle":"solid"
      },
      "PointerPoms":{
        "l":32,
        "t":32,
        "w":132,
        "h":132,
        "borderWidth":"var(--border-size-2)",
        "borderStyle":"solid"
      }
    },
    "UXToolbar$UXToolbar$actions":[
      {
        "name":"red",
        "ligature":"palette",
        "style":"background-color: red; border-radius: 25px; color: hsla(292, 3%, 20%, 1)",
        "action":"set",
        "stateKey":"PointerPoms$PointerPoms$color",
        "value":"red"
      },
      {
        "name":"orange",
        "ligature":"palette",
        "style":"background-color: orange; border-radius: 25px; color: hsla(292, 3%, 20%, 1)",
        "action":"set",
        "stateKey":"PointerPoms$PointerPoms$color",
        "value":"orange"
      },
      {
        "name":"yellow",
        "ligature":"palette",
        "style":"background-color: yellow; border-radius: 25px; color: hsla(292, 3%, 20%, 1)",
        "action":"set",
        "stateKey":"PointerPoms$PointerPoms$color",
        "value":"yellow"
      },
      {
        "name":"green",
        "ligature":"palette",
        "style":"background-color: green; border-radius: 25px",
        "action":"set",
        "stateKey":"PointerPoms$PointerPoms$color",
        "value":"green"
      },
      {
        "name":"lightblue",
        "ligature":"palette",
        "style":"background-color: lightblue; border-radius: 25px; color: hsla(292, 3%, 20%, 1)",
        "action":"set",
        "stateKey":"PointerPoms$PointerPoms$color",
        "value":"lightblue"
      },
      {
        "name":"blue",
        "ligature":"palette",
        "style":"background-color: blue; border-radius: 25px",
        "action":"set",
        "stateKey":"PointerPoms$PointerPoms$color",
        "value":"blue"
      },
      {
        "name":"purple",
        "ligature":"palette",
        "style":"background-color: purple; border-radius: 25px",
        "action":"set",
        "stateKey":"PointerPoms$PointerPoms$color",
        "value":"purple"
      },
      {
        "name":"grey",
        "ligature":"palette",
        "style":"background-color: grey; border-radius: 25px; color: hsla(292, 3%, 20%, 1)",
        "action":"set",
        "stateKey":"PointerPoms$PointerPoms$color",
        "value":"grey"
      },
      {
        "name":"white",
        "ligature":"palette",
        "style":"background-color: white; border-radius: 25px; color: hsla(292, 3%, 20%, 1)",
        "action":"set",
        "stateKey":"PointerPoms$PointerPoms$color",
        "value":"white"
      }
    ],
    "Image3$image$selfie":true,
    "Panel$panel$center":true,
    "PointerPoms$PointerPoms$penSize":2
  },
  "connections":{
    "FrameCapture$FrameCapture$stream":"DeviceUx$defaultStream$stream",
    "Holistic$SelfieSegmentation$image":"FrameCapture$FrameCapture$frame",
    "ImageComposite$ImageComposite$imageA":"FrameCapture$FrameCapture$frame",
    "ImageComposite$ImageComposite$imageB":"PointerPoms$PointerPoms$image",
    "Image3$image$image":"ImageComposite$ImageComposite$output",
    "Holistic$holistic$image":"FrameCapture$FrameCapture$frame",
    "VirtualPointer$VirtualPointer$results":"Holistic$holistic$results",
    "PointerPoms$PointerPoms$tracking":"VirtualPointer$VirtualPointer$tracking"
  }
};
