/**
 * @license
 * Copyright 2023 Atom54 LLC
 * SPDX-License-Identifier: BSD-3-Clause
 */

// TODO: This is WIP - rendering is not right.

export const graph = {
  "meta":{
    "id":"GameOn"
  },
  "PixiApp":{
    "type":"$anewLibrary/PixiJs/Atoms/PixiApp",
    "container":"Panel#Container",
    "state":{
      "active":true,
      "style":{
        "order":"2",
        "position":"relative"
      }
    }
  },
  "PixiGems":{
    "type":"$anewLibrary/PixiJs/Atoms/PixiGems",
    "container":"PixiApp#Container",
    "state":{
      "cols":5,
      "rows":4,
      "size":176,
      "margin":1,
      "style":{
        "flex":"",
        "order":"3",
        "position":""
      }
    },
    "connections":{
      "bundle":"PupsBundle$value"
    }
  },
  "PixiSprite":{
    "type":"$anewLibrary/PixiJs/Atoms/PixiSprite",
    "container":"PixiApp#Container",
    "state":{
      "from":"../Library/Assets/kittens/logo.png",
      "r":0,
      "style":{
        "display":"none"
      }
    }
  },
  "Panel":{
    "type":"$anewLibrary/Layout/Atoms/Panel",
    "container":"Container",
    "state":{
      "layout":"column",
      "style":{
        "flex":"",
        "order":"2",
        "position":"relative"
      }
    }
  },
  "Data":{
    "type":"$anewLibrary/Data/Atoms/Data",
    "container":"Container",
    "state":{
      "json":{
        "sprite0":"$anewLibrary/assets/gems/stone_blue.png",
        "sprite1":"$anewLibrary/assets/gems/stone_green.png",
        "sprite2":"$anewLibrary/assets/gems/stone_pink.png",
        "sprite3":"$anewLibrary/assets/gems/stone_yellow.png"
      }
    }
  },
  "KittensBundle":{
    "type":"$anewLibrary/Data/Atoms/Data",
    "container":"Container",
    "state":{
      "json":{
        "sprite0":"$anewLibrary/Assets/kittens/kitten0.png",
        "sprite1":"$anewLibrary/Assets/kittens/kitten1.png",
        "sprite2":"$anewLibrary/Assets/kittens/kitten2.png",
        "sprite3":"$anewLibrary/Assets/kittens/kitten3.png"
      }
    }
  },
  "Image":{
    "type":"$anewLibrary/Media/Atoms/Image",
    "container":"Container",
    "state":{
      "image":{
        "url":"../Library/Assets/pups/dogs.png"
      },
      "style":{
        "l":64,
        "t":16,
        "w":868,
        "h":525,
        "position":"absolute"
      }
    }
  },
  "PupsBundle":{
    "type":"$anewLibrary/Data/Atoms/Data",
    "container":"Container",
    "state":{
      "json":{
        "sprite0":"$anewLibrary/Assets/pups/pup0.png",
        "sprite1":"$anewLibrary/Assets/pups/pup1.png",
        "sprite2":"$anewLibrary/Assets/pups/pup2.png",
        "sprite3":"$anewLibrary/Assets/pups/pup3.png"
      }
    }
  }
};
