const graph = {
  "meta":{
    "id":"ImageSearch"
  },
  "Panel":{
    "type":"$anewLibrary/Layout/Atoms/Panel",
    "container":"Container",
    "state":{
      "layout":"column",
      "center":false,
      "style":{
        "borderWidth":"var(--border-size-3)",
        "flex":"1",
        "borderRadius":"var(--radius-4)",
        "backgroundColor":"var(--xcolor-two)",
        "color":"var(--xcolor-two)",
        "padding":"var(--size-4)",
        "order":"1",
        "width":"auto"
      }
    }
  },
  "TextField":{
    "type":"$anewLibrary/Fields/Atoms/TextField",
    "container":"Panel2#Container",
    "state":{
      "label":"Find an image:",
      "style":{
        "order":"1",
        "padding":"var(--size-2)",
        "color":"var(--xcolor-four)"
      }
    }
  },
  "Pixabay":{
    "type":"$anewLibrary/Pixabay/Atoms/PixabayImage",
    "container":"Panel#Container",
    "state":{
      "style":{
        "order":"3"
      }
    },
    "connections":{
      "query":"TextField$value",
      "trigger":"Button$value"
    }
  },
  "Panel2":{
    "type":"$anewLibrary/Layout/Atoms/Panel",
    "container":"Panel#Container",
    "state":{
      "layout":"row",
      "style":{
        "width":"auto",
        "height":"auto",
        "order":2,
        "flex":"0 0 auto"
      }
    }
  },
  "Button":{
    "type":"$anewLibrary/Fields/Atoms/Button",
    "container":"Panel2#Container",
    "state":{
      "action":"toggle",
      "label":"Find",
      "style":{
        "order":"2",
        "padding":"var(--size-2)",
        "padding-top":"var(--size-4)",
        "max-width":"100px"
      }
    }
  }
};
