const graph = {
  "meta":{
    "id":"OpenAIQnA"
  },
  "AskText":{
    "type":"$anewLibrary/Fields/Atoms/TextField",
    "container":"VerticalPanel#Container",
    "state": {
      "label":"question",
      "style":{
        "height":"auto",
        "order":1,
        "padding":"var(--size-3)",
        "backgroundColor":"var(--xcolor-one)",
        "flex":1,
        "width":"auto"
      }
    },
    "connections":{
      "value":[
        "Listen$transcript"
      ]
    }
  },
  "AnswerText":{
    "type":"$anewLibrary/Fields/Atoms/StaticText",
    "container":"Container",
    "state":{
      "style":{
        "borderWidth":"var(--border-size-1)",
        "borderStyle":"solid",
        "height":"auto",
        "backgroundColor":"var(--xcolor-one)",
        "padding":"var(--size-3)",
        "flex":1,
        "order":4,
        "borderRadius":"var(--radius-3)",
        "width":"auto"
      }
    },
    "connections":{
      "text":[
        "OpenAIText$result"
      ]
    }
  },
  "OpenAIText":{
    "type":"$anewLibrary/OpenAI/Atoms/OpenAIText",
    "container":"Container",
    "state":{
      "context":"provide brief informative answer to questions;\n",
      "enabled":true,
      "style":{}
    },
    "connections":{
      "prompt":[
        "AskText$value"
      ],
      "restart":[
        "Button$value"
      ]
    }
  },
  "ProgressBar":{
    "type":"$anewLibrary/UX/Atoms/ProgressBar",
    "container":"Container",
    "state":{
      "height":2,
      "interval":100,
      "style":{
        "borderWidth":"0px",
        "borderStyle":"solid",
        "height":"auto",
        "backgroundColor":"var(--xcolor-one)",
        "order":3,
        "padding":"var(--size-2)",
        "width":"auto"
      }
    },
    "connections":{
      "inProgress":[
        "OpenAIText$working"
      ]
    }
  },
  "Button":{
    "type":"$anewLibrary/Fields/Atoms/Button",
    "container":"VerticalPanel#Container",
    "state":{
      "action":"toggle",
      "label":"Ask",
      "style":{
        "order":2,
        "height":"auto",
        "width":"auto",
        "padding":"var(--size-3)",
        "justifyContent":"end"
      }
    }
  },
  "VerticalPanel":{
    "type":"$anewLibrary/Layout/Atoms/Panel",
    "container":"Container",
    "state":{
      "layout":"row",
      "style":{
        "order":2,
        "borderWidth":"var(--border-size-1)",
        "borderStyle":"solid",
        "height":"auto",
        "borderRadius":"var(--radius-3)",
        "flex":"",
        "width":"auto",
        "justifyContent":"start"
      }
    }
  },
  "DeviceUx":{
    "type":"$anewLibrary/Media/Atoms/DeviceUx",
    "container":"Container",
    "state": {
      "style":{}
    },
    "connections": {
      "mediaDevices": ["MediaStream$mediaDevices"],
      "mediaDeviceState": [
        "Listen$mediaDeviceState",
        "Speak$mediaDeviceState"
      ]
    }
  },
  "MediaStream": {
    "type":"$anewLibrary/Media/Atoms/MediaStream",
    "container":"Container",
    "state": {},
    "connections": {
      "mediaDeviceState": [
        "DeviceUx$mediaDeviceState"
      ]
    }
  },
  "Listen":{
    "type":"$anewLibrary/Media/Atoms/SpeechRecognizer",
    "container":"Container",
    "state": {
      "style":{}
    },
    "connections": {
      "mediaDeviceState": [
        "DeviceUx$mediaDeviceState"
      ]
    }
  },
  "Speak":{
    "type":"$anewLibrary/Media/Atoms/SpeechSynthesizer",
    "container":"Container",
    "state": {
      "style":{}
    },
    "connections":{
      "mediaDeviceState":[
        "DeviceUx$mediaDeviceState"
      ],
      "transcript":[
        "OpenAIText$result"
      ]
    }
  }
};
