const graph = {
  "meta":{
    "id":"Translate"
  },
  "fromLang":{
    "type":"$anewLibrary/Fields/Atoms/SelectField",
    "container":"Panel#Container",
    "state": {
      "label":"From",
      "value":"en",
      "style":{
        "l":64,
        "t":32,
        "w":203,
        "h":48,
        "borderWidth":"0",
        "borderStyle":"solid",
        "width":"auto",
        "height":"auto",
        "flex":"1",
        "order":"1",
        "padding":""
      }
    },
    "connections":{
      "options":["Languages$value"]
    }  
  },
  "toLang":{
    "type":"$anewLibrary/Fields/Atoms/SelectField",
    "container":"Panel#Container",
    "state": {
      "label":"To",
      "value":"es",
      "style":{
        "l":263,
        "t":8,
        "w":255,
        "h":112,
        "borderWidth":"0",
        "borderStyle":"solid",
        "width":"auto",
        "height":"auto",
        "flex":"1",
        "order":"2",
        "padding":"",
        "fontSize":""
      }
    },
    "connections":{
      "options":["Languages$value"]
    }  
  },
  "Panel":{
    "type":"$anewLibrary/Layout/Atoms/Panel",
    "container":"Panel2#Container",
    "state": {
      "layout":"row",
      "style":{
        "l":0,
        "t":0,
        "w":530,
        "h":58,
        "borderWidth":"0",
        "borderStyle":"solid",
        "order":"1",
        "height":"auto",
        "padding":"var(--size-3)",
        "color":"var(--xcolor-four)",
        "width":"auto"
      }
    }
  },
  "TranslationRes":{
    "type":"$anewLibrary/Fields/Atoms/TextArea",
    "container":"Panel2#Container",
    "state": {
      "label":"Translation",
      "style":{
        "borderWidth":"0",
        "borderStyle":"solid",
        "order":"5",
        "flex":"1",
        "width":"auto",
        "color":"var(--xcolor-four)",
        "padding":""
      }
    },
    "connections": {
      "text":["Translate$translate$translation"]
    }
  },
  "Languages":{
    "type":"$anewLibrary/Data/Atoms/Data",
    "container":"Container",
    "state": {
      "json":[
        {
          "key":"en",
          "name":"English"
        },
        {
          "key":"de",
          "name":"German"
        },
        {
          "key":"es",
          "name":"Spanish"
        },
        {
          "key":"fr",
          "name":"French"
        },
        {
          "key":"it",
          "name":"Italian"
        },
        {
          "key":"ja",
          "name":"Japanese"
        },
        {
          "key":"nl",
          "name":"Dutch"
        },
        {
          "key":"ru",
          "name":"Russian"
        },
        {
          "key":"zh",
          "name":"Chinese"
        }
      ]
    }
  },
  "Translate":{
    "type":"$anewLibrary/Locale/Atoms/Translate",
    "container":"Container",
    "state": {
      "enabled":true
    },
    "connections":{
      "inLang":["fromLang$field$value"],
      "outLang":["toLang$field$value"],
      "text":["Text$field$text"],
      "trigger":["Button$button$value"]
    }  
  },
  "Panel2":{
    "type":"$anewLibrary/Layout/Atoms/Panel",
    "container":"Container",
    "state": {
      "layout":"column",
      "style":{
        "borderWidth":"var(--border-size-4)",
        "borderStyle":"solid",
        "order":"4",
        "flex":"1",
        "color":"violet",
        "padding":"",
        "borderRadius":"var(--radius-4)",
        "width":"auto"
      }
    }
  },
  "ProgressBar":{
    "type":"$anewLibrary/UX/Atoms/ProgressBar",
    "container":"Panel2#Container",
    "state": {
      "height":2,
      "interval":200,
      "style":{
        "borderWidth":"",
        "borderStyle":"solid",
        "height":"auto",
        "order":"4",
        "width":"auto"
      }
    },
    "connections":{
      "inProgress":["Translate$translate$working"]
    }  
  },
  "Button":{
    "type":"$anewLibrary/Fields/Atoms/Button",
    "container":"Panel2#Container",
    "state": {
      "action":"toggle",
      "label":"Translate",
      "style":{
        "width":"auto",
        "height":"auto",
        "order":"3",
        "alignItems":"center",
        "padding":"var(--size-2)"
      }
    }
  },
  "Text":{
    "type":"$anewLibrary/Fields/Atoms/TextArea",
    "container":"Panel2#Container",
    "state": {
      "label":"Text",
      "style":{
        "width":"auto",
        "order":"2",
        "color":"var(--xcolor-four)",
        "padding":"",
        "flex":"1"
      }
    }
  }
};
