/**
 * @license
 * Copyright 2023 Atom54 LLC
 * SPDX-License-Identifier: BSD-3-Clause
 */

const graph = {
  "meta":{
    "id":"VideoBackgroundGen"
  },
  "SelfieSegmentation":{
    "type":"$anewLibrary/Mediapipe/Atoms/SelfieSegmentation",
    "container":"Container",
    "state":{
      "style":{
        "borderWidth":"0",
        "borderStyle":"solid"
      }
    },
    "connections":{
      "image":[
        "FrameCapture$frame"
      ]
    }
  },
  "ImageComposite":{
    "type":"$anewLibrary/Media/Atoms/ImageComposite",
    "container":"Container",
    "state":{
      "opA":"source-over",
      "opB":"source-over",
      "opC":"destination-out",
      "opD":"destination-atop"
    },
    "connections":{
      "imageA":[
        "FrameCapture$frame"
      ],
      "imageB":[
        "OpenAIImage$image"
      ],
      "imageC":[
        "SelfieSegmentation$mask"
      ],
      "imageD":[
        "FrameCapture$frame"
      ]
    }
  },
  "Image2":{
    "type":"$anewLibrary/Media/Atoms/Image",
    "container":"Panel#Container",
    "state":{
      "image":{
        "alt":"no image"
      },
      "selfie":true,
      "style":{
        "borderWidth":"0",
        "flex":"1",
        "order":"4",
        "borderRadius":""
      }
    },
    "connections":{
      "image":[
        "ImageComposite$output"
      ]
    }
  },
  "OpenAIImage":{
    "type":"$anewLibrary/OpenAI/Atoms/OpenAIImage",
    "container":"Container",
    "state":{
      "enabled":true,
      "style":{
        "borderWidth":"0",
        "borderStyle":"solid",
        "order":"9"
      }
    },
    "connections":{
      "prompt":[
        "TextField$value"
      ],
      "restart":[
        "Button$value"
      ]
    }
  },
  "TextField":{
    "type":"$anewLibrary/Fields/Atoms/TextField",
    "container":"Panel2#Container",
    "state":{
      "value":"",
      "label":"Choose background:",
      "style":{
        "borderWidth":"0",
        "flex":"1",
        "order":"1",
        "color":"var(--xcolor-four)"
      }
    }
  },
  "Panel":{
    "type":"$anewLibrary/Layout/Atoms/Panel",
    "container":"Container",
    "state":{
      "layout":"column",
      "center":false,
      "style":{
        "borderWidth":"var(--border-size-4)",
        "flex":"1",
        "order":"1",
        "padding":"var(--size-3)",
        "backgroundColor":"var(--xcolor-two)",
        "color":"var(--xcolor-two)",
        "borderRadius":"var(--radius-5)"
      }
    }
  },
  "ProgressBar":{
    "type":"$anewLibrary/UX/Atoms/ProgressBar",
    "container":"Panel#Container",
    "state":{
      "height":3,
      "interval":100,
      "style":{
        "order":"3",
        "padding":"var(--size-2)"
      }
    },
    "connections":{
      "inProgress":[
        "OpenAIImage$working"
      ]
    }
  },
  "Panel2":{
    "type":"$anewLibrary/Layout/Atoms/Panel",
    "container":"Panel#Container",
    "state":{
      "layout":"row",
      "style":{
        "borderWidth":"0",
        "order":"2"
      }
    }
  },
  "Button":{
    "type":"$anewLibrary/Fields/Atoms/Button",
    "container":"Panel2#Container",
    "state":{
      "action":"toggle",
      "label":"Generate",
      "inverted":false,
      "style":{
        "order":"2"
      }
    }
  }
};
